name: Build LaTeX PDF
on: 
  push:
    tags:
      - '**'
jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: read
    steps:
    - name: Set up Git repository
      uses: actions/checkout@v2
    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v3
      with:
          # The root LaTeX file to be compiled
          root_file: main.tex
          latexmk_shell_escape: true
          args: -pdf -file-line-error -f -halt-on-error -interaction=nonstopmode
          extra_system_packages: "inkscape"
          post_compile: latexmk -c
    - name: Add file to release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          main.pdf
        make_latest: true